AWSTemplateFormatVersion: 2010-09-09


Resources:

  EcrRepositoryApi:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: api

  InfraArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", ["infra-artifacts", !Ref "AWS::AccountId"]]

## Output Values
Outputs:
  InfraArtifactsBucket:
    Description: Artifact Bucket
    Value: !Ref "InfraArtifactsBucket"

  EcrRepositoryApiArn:
    Description: Users ECR Repository Arn
    Value: !GetAtt EcrRepositoryApi.Arn